package:
  name: ca-certificates
  version: "20241121"
  epoch: 42
  description: CA certificates from the Mozilla trusted root program
  commit: cfbfc5c7500721e9c6e95221587c5d6943cddda5
  copyright:
    - license: MPL-2.0 AND MIT
  dependencies:
    runtime:
      - merged-usrsbin
      - wolfi-baselayout
  resources: {}
environment:
  contents:
    build_repositories:
      - https://apk.cgr.dev/chainguard
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - binutils=2.44-r2
      - build-base=1-r8
      - busybox=1.37.0-r40
      - ca-certificates-bundle=20241121-r41
      - cyrus-sasl=2.1.28-r40
      - gcc=14.2.0-r12
      - gdbm=1.25-r0
      - git=2.49.0-r1
      - glibc-dev=2.41-r4
      - glibc-locale-posix=2.41-r4
      - glibc=2.41-r4
      - gmp=6.3.0-r4
      - heimdal-libs=7.8.0-r40
      - isl=0.27-r0
      - jitterentropy-library-dev=3.6.3-r1
      - jitterentropy-library=3.6.3-r1
      - keyutils-libs=1.6.3-r31
      - krb5-conf=1.0-r6
      - krb5-libs=1.21.3-r40
      - ld-linux=2.41-r4
      - libatomic=14.2.0-r12
      - libbrotlicommon1=1.1.0-r4
      - libbrotlidec1=1.1.0-r4
      - libbz2-1=1.0.8-r11
      - libcom_err=1.47.2-r21
      - libcrypt1=2.41-r4
      - libcrypto3=3.5.0-r2
      - libcurl-openssl4=8.14.0-r0
      - libexpat1=2.7.1-r0
      - libgcc=14.2.0-r12
      - libgo=14.2.0-r12
      - libgomp=14.2.0-r12
      - libidn2=2.3.8-r0
      - libldap=2.6.10-r0
      - libnghttp2-14=1.65.0-r0
      - libpcre2-8-0=10.45-r1
      - libpsl=0.21.5-r4
      - libquadmath=14.2.0-r12
      - libssl3=3.5.0-r2
      - libstdc++-dev=14.2.0-r12
      - libstdc++=14.2.0-r12
      - libunistring=1.3-r1
      - libverto=0.3.2-r4
      - libxcrypt-dev=4.4.38-r1
      - libxcrypt=4.4.38-r1
      - libzstd1=1.5.7-r1
      - linux-headers=6.15-r0
      - make=4.4.1-r4
      - mpc=1.3.1-r5
      - mpfr=4.2.2-r0
      - ncurses-terminfo-base=6.5_p20241228-r1
      - ncurses=6.5_p20241228-r1
      - nss-db=2.41-r4
      - nss-hesiod=2.41-r4
      - openssf-compiler-options=20240627-r20
      - openssl-dev=3.5.0-r2
      - patch=2.8-r0
      - perl=5.40.2-r0
      - pkgconf=2.4.3-r1
      - posix-cc-wrappers=1-r6
      - readline=8.2.13-r3
      - sqlite-libs=3.49.2-r0
      - wolfi-baselayout=20230201-r20
      - zlib=1.3.1-r7
  accounts:
    run-as: ""
    users:
      - username: build
        uid: 1000
        gid: 1000
        shell: ""
        homedir: /home/build
    groups:
      - groupname: build
        gid: 1000
        members:
          - build
  archs:
    - amd64
  environment:
    GOFLAGS: ""
    GOMODCACHE: /var/cache/melange/gomodcache
    GOPATH: /home/build/.cache/go
    GOTOOLCHAIN: local
    HOME: /home/build
    PYTHONHASHSEED: "0"
pipeline:
  - uses: git-checkout
    with:
      expected-commit: 35fc750804a78979c392a151aee12ce69e618713
      repository: https://gitlab.alpinelinux.org/alpine/ca-certificates
      tag: "20241121"
    pipeline:
      - runs: |
          #!/bin/sh
          set -e
          msg() { echo "[git checkout]" "$@"; }
          fail() {
          	msg FAIL "$@"
          	exit 1
          }
          vr() {
          	msg "execute:" "$@"
          	"$@"
          }
          process_cherry_picks() {
          	local cpicksf="$1" oifs="$IFS" count=0
          	local fetched_branches=""
          	local sdate=${SOURCE_DATE_EPOCH:-0}
          	if [ "$sdate" -lt 315532800 ]; then
          		msg "Setting commit date to Jan 1, 1980 (SOURCE_DATE_EPOCH found ${SOURCE_DATE_EPOCH})"
          		sdate=315532800
          	fi
          	if [ -z "$cpicksf" ]; then
          		return 0
          	fi
          	if [ ! -f "$cpicksf" ]; then
          		msg "cherry picks input '$cpicksf' is not a file"
          		return 1
          	fi

          	local line="" branch="" hash="" comment=""
          	while IFS= read -r line; do

          		line=${line%%#*}
          		[ -z "$line" ] && continue

          		if ! echo "$line" | grep -q ':'; then
          			msg "Invalid format, expected '[branch/]commit: comment'. Found: $line"
          			return 1
          		fi

          		branch=${line%%:*}
          		comment=${line#*:}
          		comment=$(
          			set -f
          			echo $comment
          		)

          		if [ -z "$comment" ]; then
          			msg "Empty comment for cherry-pick: $line"
          			return 1
          		fi

          		hash=${branch##*/}

          		[ "$branch" != "$hash" ] && branch=${branch%/*} || branch=""

          		if [ -n "$branch" ]; then
          			case " $fetched_branches " in
          			*" $branch "*) ;;
          			*)
          				vr git fetch origin $branch:$branch || {
          					msg "failed to fetch branch $branch"
          					return 1
          				}
          				fetched_branches="$fetched_branches $branch "
          				;;
          			esac
          		fi

          		vr env \
          			GIT_COMMITTER_DATE="@$sdate" \
          			git cherry-pick -x "$hash" || {
          			msg "failed to cherry-pick $hash from branch $branch"
          			return 1
          		}

          		msg "Cherry-picked $hash from $branch with comment: $comment"

          		count=$((count + 1))
          	done <"$cpicksf"

          	if [ $count -gt 0 ]; then
          		msg "applied $count cherry-pick(s). head is now $(git rev-parse HEAD)"
          	fi
          }
          main() {
          	local repo=$1 dest=${2:-.} depth=${3:-"unset"} branch=$4
          	local tag=$5 expcommit=$6 recurse=${7:-false}
          	local cherry_pick="$8"
          	msg "repo='$repo' dest='$dest' depth='$depth' branch='$branch'" \
          		"tag='$tag' expcommit='$expcommit' recurse='$recurse'"

          	case "$recurse" in
          	true | false) : ;;
          	*) fail "recurse must be true or false, not '$recurse'" ;;
          	esac

          	[ -n "$repo" ] || fail "repository not provided"

          	if [ -z "$branch" ] && [ -z "$tag" ]; then
          		msg "Warning: you have not specified a branch or tag."
          	elif [ -n "$branch" ] && [ -n "$tag" ]; then
          		fail "both branch ($branch) and tag ($tag) are specified."
          	fi

          	[ -n "$expcommit" ] ||
          		msg "Warning: no expected-commit"

          	local flags="" depthflag="" dest_fullpath="" workdir=""
          	local remote="origin" rcfile="" rc="" quiet="--quiet"
          	flags="--config=advice.detachedHead=false"
          	[ -n "$branch" ] && flags="$flags --branch=$branch"
          	[ -n "$tag" ] && flags="$flags --branch=$tag"
          	[ "$recurse" = "true" ] && flags="$flags --recurse-submodules"

          	if [ "$depth" = "unset" ]; then
          		depth=1
          		if [ -n "$branch" -a -n "$expcommit" ]; then

          			depth=-1
          		fi
          	fi

          	[ "$depth" = "-1" ] || depthflag="--depth=$depth"

          	workdir=$(mktemp -d)
          	rcfile=$(mktemp)
          	mkdir -p "$dest"
          	dest_fullpath=$(realpath "$dest")

          	vr git config --global --add safe.directory "$workdir"
          	vr git config --global --add safe.directory "$dest_fullpath"

          	vr git clone $quiet "--origin=$remote" \
          		"--config=user.name=Melange Build" \
          		"--config=user.email=melange-build@cgr.dev" \
          		$flags \
          		${depthflag:+"$depthflag"} "$repo" "$workdir"

          	vr cd "$workdir"
          	msg "tar -c . | tar -C \"$dest_fullpath\" -x"
          	(
          		tar -c .
          		echo $? >"$rcfile"
          	) | tar -C "$dest_fullpath" -x --no-same-owner
          	read rc <"$rcfile" || fail "failed to read rc file"
          	[ $rc -eq 0 ] || fail "tar creation in $workdir failed"

          	rm -rf "$workdir"
          	vr cd "$dest_fullpath"
          	vr git config --global --add safe.directory "$dest_fullpath"

          	local foundcommit="" tagobj=""
          	if [ -z "$tag" ]; then
          		foundcommit=$(git rev-parse --verify HEAD)
          		if [ -n "$expcommit" ] && [ "$expcommit" != "$foundcommit" ]; then
          			if [ "$depth" = "-1" ]; then
          				msg "expected commit $expcommit on ${branch:-HEAD}," \
          					"got $foundcommit, performing reset"
          				vr git reset --hard "$expcommit"
          			else
          				fail "expected commit $expcommit on ${branch:-HEAD}," \
          					"got $foundcommit, set depth to -1 to attempt a reset"
          			fi
          		fi
          		msg "tip of ${branch:-HEAD} is commit $foundcommit"
          		process_cherry_picks "$cherry_pick" || fail "failed to apply cherry-pick"
          		return 0
          	fi

          	vr git fetch $quiet $remote ${depthflag:-"$depthflag"} --no-tags \
          		"+refs/tags/$tag:refs/$remote/tags/$tag"
          	vr git checkout $quiet "$remote/tags/$tag"

          	foundcommit=$(git rev-parse --verify HEAD)
          	if [ -z "$expcommit" ] || [ "$expcommit" = "$foundcommit" ]; then
          		msg "tag $tag is $foundcommit"
          	else

          		tagobj=$(git rev-parse --verify --end-of-options \
          			"refs/$remote/tags/$tag")
          		if [ "$expcommit" != "$tagobj" ]; then
          			[ "$tagobj" != "$expcommit" ] &&
          				msg "tag object hash was $tagobj"
          			fail "Expected commit $expcommit for $tag, found $foundcommit"
          		fi

          		msg "Warning: The provided expected-commit ($expcommit)"
          		msg "was the hash of the annotated tag object for $tag."
          		msg "Update to set expected-commit to $foundcommit"
          	fi

          	process_cherry_picks "$cherry_pick" ||
          		fail "failed to apply cherry-pick"

          	return 0
          }
          cpickf=$(mktemp) || {
          	echo "failed mktemp"
          	exit 1
          }
          cat >"$cpickf" <<"END_CHERRY_PICKS"

          END_CHERRY_PICKS
          main \
          	"https://gitlab.alpinelinux.org/alpine/ca-certificates" "." \
          	"unset" "" \
          	"20241121" "35fc750804a78979c392a151aee12ce69e618713" \
          	"false" "$cpickf"
          rm -f "$cpickf"
  - uses: patch
    with:
      patches: entrust.patch
    pipeline:
      - runs: |
          series=''
          if [ -z $series ]; then
          	if [ -n 'entrust.patch' ]; then
          		series=$(mktemp)
          		echo 'entrust.patch' | awk '{ for(i = 1; i <= NF; i++) { print $i; } }' >$series
          	else
          		echo "ERROR: Neither patches or series was set."
          		exit 1
          	fi
          fi
          grep -v -E '^(#|$)' $series | (while read patchfile; do
          	patch '-p1' --fuzz=2 --verbose <$patchfile
          done)
  - runs: |
      make CC="x86_64-pc-linux-gnu-gcc"
  - runs: |
      make install DESTDIR="/home/build/melange-out/ca-certificates"
      mv /home/build/melange-out/ca-certificates/usr/sbin/* /home/build/melange-out/ca-certificates/usr/bin/
      rmdir /home/build/melange-out/ca-certificates/usr/sbin
      (
      	echo "# Automatically generated by ca-certificates-20241121-r42"
      	echo "# Do not edit."
      	cd "/home/build/melange-out/ca-certificates"/usr/share/ca-certificates
      	find . -name '*.crt' | sort | cut -b3-
      ) >"/home/build/melange-out/ca-certificates"/etc/ca-certificates.conf
      for i in $(ls *.crt | sort); do
      	cat "$i"
      	printf "\n"
      done >"/home/build/melange-out/ca-certificates"/etc/ssl/certs/ca-certificates.crt
      mkdir -p "/home/build/melange-out/ca-certificates"/etc/apk/protected_paths.d
      cat >"/home/build/melange-out/ca-certificates"/etc/apk/protected_paths.d/ca-certificates.list <<-EOF
      	  -etc/ssl/certs/ca-certificates.crt
      	  -etc/ssl/certs/ca-cert-*.pem
      	  -etc/ssl/certs/[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f].[r0-9]*
      EOF
      cat >"/home/build/melange-out/ca-certificates"/etc/ca-certificates/update.d/certhash <<-EOF
      	  #!/bin/sh
      	  exec /usr/bin/c_rehash /etc/ssl/certs
      EOF
      chmod +x "/home/build/melange-out/ca-certificates"/etc/ca-certificates/update.d/certhash
subpackages:
  - name: ca-certificates-bundle
    pipeline:
      - runs: |
          mkdir -p "/home/build/melange-out/ca-certificates-bundle"/etc/ssl/certs
          mv "/home/build/melange-out/ca-certificates"/etc/ssl/certs/ca-certificates.crt "/home/build/melange-out/ca-certificates-bundle"/etc/ssl/certs
          ln -s certs/ca-certificates.crt "/home/build/melange-out/ca-certificates-bundle"/etc/ssl/cert.pem
          mkdir -p /home/build/melange-out/ca-certificates-bundle/etc/pki/tls/certs/
          ln -s ../../../ssl/certs/ca-certificates.crt /home/build/melange-out/ca-certificates-bundle/etc/pki/tls/certs/ca-bundle.crt
          mkdir -p /home/build/melange-out/ca-certificates-bundle/etc/ssl/certs/
          ln -s ca-certificates.crt /home/build/melange-out/ca-certificates-bundle/etc/ssl/certs/ca-bundle.crt
    dependencies:
      runtime:
        - merged-usrsbin
        - wolfi-baselayout
    commit: cfbfc5c7500721e9c6e95221587c5d6943cddda5
    test:
      environment:
        contents:
          packages:
            - ca-certificates-bundle
        accounts:
          run-as: ""
          users:
            - username: build
              uid: 1000
              gid: 1000
              shell: ""
              homedir: ""
          groups:
            - groupname: build
              gid: 1000
              members:
                - build
      pipeline:
        - name: test for certs directory
          runs: |
            if [ -d "/etc/ssl/certs" ]; then
            	echo "certs directory exists"
            else
            	echo "certs directory does not exist"
            	exit 1
            fi
        - name: test for cert.pem file
          runs: |
            if [ -s "/etc/ssl/cert.pem" ]; then
            	echo "file exists and contains contents."
            else
            	echo "cert.pem file does not exist or is empty"
            	exit 1
            fi
        - name: test for ca-bundle.crt file
          runs: |
            if [ -s "/etc/pki/tls/certs/ca-bundle.crt" ]; then
            	echo "file exists and contains contents."
            else
            	echo "ca-bundle.crt file does not exist or is empty"
            	exit 1
            fi
  - name: ca-certificates-doc
    pipeline:
      - uses: split/manpages
        pipeline:
          - runs: |
              PACKAGE_DIR="/home/build/melange-out/ca-certificates"
              if [ -n "" ]; then
              	PACKAGE_DIR="/home/build/melange-out/"
              fi
              if [ "$PACKAGE_DIR" == "/home/build/melange-out/ca-certificates-doc" ]; then
              	echo "ERROR: Package can not split files from itself!" && exit 1
              fi
              if [ -d "$PACKAGE_DIR/usr/share/man" ]; then
              	mkdir -p "/home/build/melange-out/ca-certificates-doc/usr/share"
              	mv "$PACKAGE_DIR/usr/share/man" "/home/build/melange-out/ca-certificates-doc/usr/share"
              fi
    description: ca-certificates documentation
    commit: cfbfc5c7500721e9c6e95221587c5d6943cddda5
    test:
      environment:
        contents:
          packages:
            - apk-tools
            - ca-certificates-doc
            - grep
            - man-db
            - texinfo
        accounts:
          run-as: ""
          users:
            - username: build
              uid: 1000
              gid: 1000
              shell: ""
              homedir: ""
          groups:
            - groupname: build
              gid: 1000
              members:
                - build
      pipeline:
        - uses: test/docs
          pipeline:
            - name: docs readability check
              runs: |
                doc_pkg=$(basename /home/build/melange-out/ca-certificates-doc)
                if [ $(apk info -qL "$doc_pkg" | grep -v "^var/lib/db/sbom" | grep -v "^$" | wc -l) -eq 0 ]; then
                	echo "See:"
                	apk info -qL "$doc_pkg"
                	echo "This package [$doc_pkg] is completely empty (i.e. installs no files)."
                	echo "Please check the package build for proper docs installation, and either:"
                	echo "  (a) fix the docs subpackage build to actually include documentation (check the split/manpages and split/infodir pipelines), or"
                	echo "  (b) remove the test/docs pipeline (if for some reason we want an empty docs package), or"
                	echo "  (c) remove the docs subpackage entirely"
                	exit 1
                fi
                cd /
                doc_files=false
                for doc_file in $(apk info -qL "$doc_pkg" | grep "^usr/share/man/"); do
                	if [ -f /"$doc_file" ]; then

                		man -l /"$doc_file" >/dev/null
                		doc_files=true
                	fi
                done
                for doc_file in $(apk info -qL "$doc_pkg" | grep "^usr/share/info/"); do
                	if [ -f /"$doc_file" ]; then

                		[ $(info -f /"$doc_file" -o - | wc -l) -gt 0 ] && doc_files=true
                	fi
                done
                for doc_file in $(apk info -qL "$doc_pkg" | grep "^usr/share/"); do
                	if [ -f /"$doc_file" ]; then

                		cat /"$doc_file" >/dev/null
                		doc_files=true
                	fi
                done
                if [ $doc_files = "false" ]; then
                	echo "See:"
                	apk info -qL "$doc_pkg"
                	echo "This package [$doc_pkg] installs files, but no usable documentation"
                	echo "Please check the package build for proper docs installation, and either:"
                	echo "  (a) fix the docs subpackage build to actually include docs (check the split/manpages and split/infodir pipelines), or"
                	echo "  (b) remove the test/docs pipeline"
                	exit 1
                fi
update:
  enabled: true
  manual: false
  require-sequential: false
  release-monitor:
    identifier: 332224
test:
  environment:
    contents:
      packages:
        - ca-certificates
        - curl
    accounts:
      run-as: ""
      users:
        - username: build
          uid: 1000
          gid: 1000
          shell: ""
          homedir: ""
      groups:
        - groupname: build
          gid: 1000
          members:
            - build
  pipeline:
    - runs: |
        ! SSL_CERT_FILE=/dev/null curl --ipv4 -v https://packages.wolfi.dev
        SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt curl --ipv4 -v https://packages.wolfi.dev
        SSL_CERT_FILE=/etc/pki/tls/certs/ca-bundle.crt curl --ipv4 -v https://packages.wolfi.dev
        SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt curl --ipv4 -v https://packages.wolfi.dev
        c_rehash -v
        update-ca-certificates --version
        update-ca-certificates --help
