package:
  name: readline
  version: 8.2.13
  epoch: 4
  description: GNU readline library
  commit: cfbfc5c7500721e9c6e95221587c5d6943cddda5
  copyright:
    - license: GPL-3.0-or-later
  resources: {}
environment:
  contents:
    build_repositories:
      - https://apk.cgr.dev/chainguard
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - binutils=2.44-r2
      - build-base=1-r8
      - busybox=1.37.0-r41
      - ca-certificates-bundle=20241121-r42
      - gcc=14.2.0-r12
      - glibc-dev=2.41-r4
      - glibc-locale-posix=2.41-r4
      - glibc=2.41-r4
      - gmp=6.3.0-r4
      - isl=0.27-r0
      - ld-linux=2.41-r4
      - libatomic=14.2.0-r12
      - libcrypt1=2.41-r4
      - libcrypto3=3.5.0-r2
      - libgcc=14.2.0-r12
      - libgo=14.2.0-r12
      - libgomp=14.2.0-r12
      - libquadmath=14.2.0-r12
      - libssl3=3.5.0-r2
      - libstdc++-dev=14.2.0-r12
      - libstdc++=14.2.0-r12
      - libxcrypt-dev=4.4.38-r1
      - libxcrypt=4.4.38-r1
      - libzstd1=1.5.7-r2
      - linux-headers=6.15-r1
      - make=4.4.1-r5
      - mpc=1.3.1-r5
      - mpfr=4.2.2-r0
      - ncurses-dev=6.5_p20241228-r2
      - ncurses-terminfo-base=6.5_p20241228-r2
      - ncurses=6.5_p20241228-r2
      - nss-db=2.41-r4
      - nss-hesiod=2.41-r4
      - openssf-compiler-options=20240627-r20
      - patch=2.8-r0
      - pkgconf=2.4.3-r2
      - posix-cc-wrappers=1-r6
      - scanelf=1.3.8-r4
      - wget=1.25.0-r1
      - wolfi-baselayout=20230201-r20
      - zlib=1.3.1-r7
  accounts:
    run-as: ""
    users:
      - username: build
        uid: 1000
        gid: 1000
        shell: ""
        homedir: /home/build
    groups:
      - groupname: build
        gid: 1000
        members:
          - build
  archs:
    - amd64
  environment:
    GOFLAGS: ""
    GOMODCACHE: /var/cache/melange/gomodcache
    GOPATH: /home/build/.cache/go
    GOTOOLCHAIN: local
    HOME: /home/build
    PYTHONHASHSEED: "0"
pipeline:
  - uses: fetch
    with:
      expected-sha256: 0e5be4d2937e8bd9b7cd60d46721ce79f88a33415dd68c2d738fb5924638f656
      purl-name: readline
      purl-version: 8.2.13
      uri: https://ftp.gnu.org/gnu/readline/readline-8.2.13.tar.gz
    pipeline:
      - runs: |
          if [ "0e5be4d2937e8bd9b7cd60d46721ce79f88a33415dd68c2d738fb5924638f656" == "" ] && [ "" == "" ]; then
          	printf "One of expected-sha256 or expected-sha512 is required"
          	exit 1
          fi
          bn=$(basename https://ftp.gnu.org/gnu/readline/readline-8.2.13.tar.gz)
          if [ ! "0e5be4d2937e8bd9b7cd60d46721ce79f88a33415dd68c2d738fb5924638f656" == "" ]; then
          	fn="/var/cache/melange/sha256:0e5be4d2937e8bd9b7cd60d46721ce79f88a33415dd68c2d738fb5924638f656"
          	if [ -f $fn ]; then
          		printf "fetch: found $fn in cache\n"
          		cp $fn $bn
          	fi
          else
          	fn="/var/cache/melange/sha512:"
          	if [ -f $fn ]; then
          		printf "fetch: found $fn in cache\n"
          		cp $fn $bn
          	fi
          fi
          if [ ! -f $bn ]; then
          	wget '-T5' '--dns-timeout=20' '--tries=5' --random-wait --retry-connrefused --continue 'https://ftp.gnu.org/gnu/readline/readline-8.2.13.tar.gz'
          fi
          if [ "0e5be4d2937e8bd9b7cd60d46721ce79f88a33415dd68c2d738fb5924638f656" != "" ]; then
          	printf "fetch: Expected sha256: 0e5be4d2937e8bd9b7cd60d46721ce79f88a33415dd68c2d738fb5924638f656\n"
          	sum=$(sha256sum $bn | awk '{print $1}')
          	if [ "0e5be4d2937e8bd9b7cd60d46721ce79f88a33415dd68c2d738fb5924638f656" != "$sum" ]; then
          		printf "fetch: Expected sha256 does not match found: $sum\n"
          		exit 1
          	fi
          else
          	printf "fetch: Expected sha512: \n"
          	sum=$(sha512sum $bn | awk '{print $1}')
          	if [ "" != "$sum" ]; then
          		printf "fetch: Expected sha512 does not match found: $sum\n"
          		exit 1
          	fi
          fi
          if [ "true" = "true" ]; then
          	tar -x '--strip-components=1' -C '.' -f $bn
          fi
          if [ "false" = "true" ]; then
          	rm $bn
          fi
  - uses: patch
    with:
      patches: fix-rl_do_undo-crash.patch
      strip-components: "0"
    pipeline:
      - runs: |
          series=''
          if [ -z $series ]; then
          	if [ -n 'fix-rl_do_undo-crash.patch' ]; then
          		series=$(mktemp)
          		echo 'fix-rl_do_undo-crash.patch' | awk '{ for(i = 1; i <= NF; i++) { print $i; } }' >$series
          	else
          		echo "ERROR: Neither patches or series was set."
          		exit 1
          	fi
          fi
          grep -v -E '^(#|$)' $series | (while read patchfile; do
          	patch '-p0' --fuzz=2 --verbose <$patchfile
          done)
  - name: Configure
    runs: |
      ./configure \
      	--host=x86_64-pc-linux-gnu \
      	--target=x86_64-pc-linux-gnu \
      	--prefix=/usr \
      	--with-shared-termcap-library
  - uses: autoconf/make
    pipeline:
      - runs: |
          make -C "." -j$(nproc) V=1
  - uses: autoconf/make-install
    pipeline:
      - runs: |
          make -C "." install DESTDIR="/home/build/melange-out/readline" V=1
      - runs: |
          find /home/build/melange-out/readline -name '*.la' -print -exec rm \{} \;
  - uses: strip
    pipeline:
      - runs: |
          scanelf --recursive --nobanner --osabi --etype "ET_DYN,ET_EXEC" . |
          	while read type osabi filename; do

          		[ "$osabi" != "STANDALONE" ] || continue

          		strip -g "${filename}" || [ ! -e "$filename" ]
          	done
        working-directory: /home/build/melange-out/readline
subpackages:
  - name: readline-doc
    pipeline:
      - uses: split/manpages
        pipeline:
          - runs: |
              PACKAGE_DIR="/home/build/melange-out/readline"
              if [ -n "" ]; then
              	PACKAGE_DIR="/home/build/melange-out/"
              fi
              if [ "$PACKAGE_DIR" == "/home/build/melange-out/readline-doc" ]; then
              	echo "ERROR: Package can not split files from itself!" && exit 1
              fi
              if [ -d "$PACKAGE_DIR/usr/share/man" ]; then
              	mkdir -p "/home/build/melange-out/readline-doc/usr/share"
              	mv "$PACKAGE_DIR/usr/share/man" "/home/build/melange-out/readline-doc/usr/share"
              fi
      - runs: |
          mkdir -p /home/build/melange-out/readline-doc/usr/share/doc
          mv /home/build/melange-out/readline/usr/share/doc/readline /home/build/melange-out/readline-doc/usr/share/doc/readline
    commit: cfbfc5c7500721e9c6e95221587c5d6943cddda5
    test:
      environment:
        contents:
          packages:
            - apk-tools
            - grep
            - man-db
            - readline-doc
            - texinfo
        accounts:
          run-as: ""
          users:
            - username: build
              uid: 1000
              gid: 1000
              shell: ""
              homedir: ""
          groups:
            - groupname: build
              gid: 1000
              members:
                - build
      pipeline:
        - uses: test/docs
          pipeline:
            - name: docs readability check
              runs: |
                doc_pkg=$(basename /home/build/melange-out/readline-doc)
                if [ $(apk info -qL "$doc_pkg" | grep -v "^var/lib/db/sbom" | grep -v "^$" | wc -l) -eq 0 ]; then
                	echo "See:"
                	apk info -qL "$doc_pkg"
                	echo "This package [$doc_pkg] is completely empty (i.e. installs no files)."
                	echo "Please check the package build for proper docs installation, and either:"
                	echo "  (a) fix the docs subpackage build to actually include documentation (check the split/manpages and split/infodir pipelines), or"
                	echo "  (b) remove the test/docs pipeline (if for some reason we want an empty docs package), or"
                	echo "  (c) remove the docs subpackage entirely"
                	exit 1
                fi
                cd /
                doc_files=false
                for doc_file in $(apk info -qL "$doc_pkg" | grep "^usr/share/man/"); do
                	if [ -f /"$doc_file" ]; then

                		man -l /"$doc_file" >/dev/null
                		doc_files=true
                	fi
                done
                for doc_file in $(apk info -qL "$doc_pkg" | grep "^usr/share/info/"); do
                	if [ -f /"$doc_file" ]; then

                		[ $(info -f /"$doc_file" -o - | wc -l) -gt 0 ] && doc_files=true
                	fi
                done
                for doc_file in $(apk info -qL "$doc_pkg" | grep "^usr/share/"); do
                	if [ -f /"$doc_file" ]; then

                		cat /"$doc_file" >/dev/null
                		doc_files=true
                	fi
                done
                if [ $doc_files = "false" ]; then
                	echo "See:"
                	apk info -qL "$doc_pkg"
                	echo "This package [$doc_pkg] installs files, but no usable documentation"
                	echo "Please check the package build for proper docs installation, and either:"
                	echo "  (a) fix the docs subpackage build to actually include docs (check the split/manpages and split/infodir pipelines), or"
                	echo "  (b) remove the test/docs pipeline"
                	exit 1
                fi
  - name: readline-dev
    pipeline:
      - uses: split/dev
        pipeline:
          - runs: |
              PACKAGE_DIR="/home/build/melange-out/readline"
              if [ -n "" ]; then
              	PACKAGE_DIR="/home/build/melange-out/"
              fi
              if [ "$PACKAGE_DIR" == "/home/build/melange-out/readline-dev" ]; then
              	echo "ERROR: Package can not split files from itself!" && exit 1
              fi
              i= j=
              cd "$PACKAGE_DIR" || exit 0
              libdirs=usr/
              [ -d lib/ ] && libdirs="lib/ $libdirs"
              for i in usr/include usr/lib/pkgconfig usr/share/pkgconfig \
              	usr/share/aclocal usr/share/gettext \
              	usr/bin/*-config usr/bin/*_config usr/share/vala/vapi \
              	usr/share/gir-[0-9]* usr/share/qt*/mkspecs \
              	usr/lib/qt*/mkspecs \
              	usr/lib/cmake usr/share/cmake \
              	usr/lib/glade/modules usr/share/glade/catalogs \
              	$(find . -name include -type d) \
              	$(find $libdirs -name '*.a' 2>/dev/null) \
              	$(find $libdirs -name '*.[cho]' \
              		-o -name '*.prl' 2>/dev/null); do
              	if [ -e "$PACKAGE_DIR/$i" ] || [ -L "$PACKAGE_DIR/$i" ]; then
              		d="/home/build/melange-out/readline-dev/${i%/*}"
              		mkdir -p "$d"
              		mv "$PACKAGE_DIR/$i" "$d"
              		rmdir "$PACKAGE_DIR/${i%/*}" 2>/dev/null || :
              	fi
              done
              for i in lib/*.so usr/lib/*.so; do
              	if [ -L "$i" ]; then
              		mkdir -p "/home/build/melange-out/readline-dev"/"${i%/*}"
              		mv "$i" "/home/build/melange-out/readline-dev/$i" || return 1
              	fi
              done
    dependencies:
      runtime:
        - readline
    description: GNU readline headers
    commit: cfbfc5c7500721e9c6e95221587c5d6943cddda5
    test:
      environment:
        contents:
          packages:
            - gcc
            - ldd-check
            - pkgconf
            - readline-dev
        accounts:
          run-as: ""
          users:
            - username: build
              uid: 1000
              gid: 1000
              shell: ""
              homedir: ""
          groups:
            - groupname: build
              gid: 1000
              members:
                - build
      pipeline:
        - uses: test/tw/ldd-check
          pipeline:
            - name: check for missing library dependencies using ldd
              runs: |
                ldd-check \
                	--files="" \
                	--packages="readline-dev" \
                	--extra-library-paths="" \
                	--verbose="false"
        - uses: test/pkgconf
          pipeline:
            - name: pkgconf build dependency check
              runs: |
                dev_pkg=$(basename /home/build/melange-out/readline-dev)
                cd /
                pc_files=false
                for pc_file in $(apk info -L "$dev_pkg" 2>/dev/null | grep "\.pc$"); do
                	pc_files=true

                	if grep -q "^Name:" $pc_file; then
                		lib_name=$(basename "$pc_file" ".pc")

                		echo "$pc_file" | grep -q "^usr/lib/pkgconfig/${lib_name}.pc$\|^usr/share/pkgconfig/${lib_name}.pc$"

                		pkgconf --exists $lib_name || pkgconf --print-errors --exists $lib_name

                		if grep -q "^Version:" $pc_file; then
                			pkgconf --modversion $lib_name
                		fi

                		if grep -q "^Libs:" $pc_file; then
                			pkgconf --libs $lib_name
                		fi

                		if grep -q "^Cflags:" $pc_file; then
                			pkgconf --cflags $lib_name
                		fi
                	fi
                done
                if [ $pc_files = "false" ]; then
                	echo "No .pc files found in $dev_pkg please remove the pkgconf test"
                fi
        - name: ncurses/tinfo linking regression check
          runs: |
            echo "int main() {}" >demo.c
            gcc -o demo demo.c -Wl,--no-as-needed -lreadline
update:
  enabled: true
  manual: false
  require-sequential: false
  release-monitor:
    identifier: 4173
test:
  environment:
    contents:
      packages:
        - ldd-check
        - readline
    accounts:
      run-as: ""
      users:
        - username: build
          uid: 1000
          gid: 1000
          shell: ""
          homedir: ""
      groups:
        - groupname: build
          gid: 1000
          members:
            - build
  pipeline:
    - uses: test/tw/ldd-check
      pipeline:
        - name: check for missing library dependencies using ldd
          runs: |
            ldd-check \
            	--files="" \
            	--packages="readline" \
            	--extra-library-paths="" \
            	--verbose="false"
